### ISSUE TITLE
make install incompatible with MKL

### ISSUE THREAD

**Issue by beckermr** [conda-forge/mpi4py-fft-feedstock#20]
It is apparently not good to install this package with MKL and there has not been a proposal to fix it yet: https://bitbucket.org/mpi4py/mpi4py-fft/issues/18/forward-fft-yields-0-with-fftw-backend-and

We should patch the builds to make this package conflict with mkl for the time being.

**Comment by dalcinl** [comment]
Patching the build will not make it. We do not use MKL at all for building. This is a runtime issue. If the mkl libraries are loaded before this package, the MKL symbols forcibly take precedence and this package no longer uses the symbols from the original FFTW libraries this package was linked to. The alternative is to use FFTW static libraries, and link with `-Bsymbolic`, which upstream does not like.

Or by patching the build do you mean somehow setting a conflict in the recipe metadata? Is that supported?

**Comment by beckermr** [comment]
Sorry yes, I meant to say that we cna patch the repodata to require `nomkl` at runtime. Patches can be submitted here: https://github.com/conda-forge/conda-forge-repodata-patches-feedstock

**Comment by beckermr** [comment]
We can also add `nomkl` as a run requirement until this is fixed upstream.

**Comment by dalcinl** [comment]
Fixed upstream by who? I don't expect Intel to ever fix the FFTW MKL wrappers. And there is little to do on `mpi4py-fft` side. At least, I have not figured it out yet.

Are you completely sure that adding the `nomkl` run requirement is the proper way to go? I'm a bit hesitant, because there are workarounds to this issue (e.g. using `LD_PRELOAD`). If we go the nomkl way, then we make it impossible to use a mkl-accelerated numpy with mpi4py-fft.

**Comment by mikaem** [comment]
We used to use nomkl, but removed it since we agreed this should be handled by users or other means. It's been awhile, so I don't quite remember.

**Comment by beckermr** [comment]
Right now as I understand it the library fails silently with MKL in the env. No user can be expected to know this right away when they are using the library for the first time, and so they encounter an extremely nasty bug where their FFTs simply don't happen. 

It is the silent failure that needs to be fixed, either by a change in mpi4py-fft or by making envs with MKL in them incompatible with this package.

**Comment by dalcinl** [comment]
@beckermr I pushed a fix into mater some time ago such that errors do not pass silently mpi4py/mpi4py-fft@5c344d2

@mikaem Perhaps we should apply that patch to the current conda-forge recipe, or perhaps even better, make a new mpi4py-fft release 2.0.4 with all the minor fixes accumulated so far?

**Comment by beckermr** [comment]
Thanks for the pointer @dalcinl!

We still need something for older versions. I'd suggest making those incompatible with mkl

**Comment by mikaem** [comment]
@dalcinl I like the fixes and agree we should make a new release.

**Comment by dalcinl** [comment]
> I'd suggest making those incompatible with mkl

@beckermr Sorry, but I have no idea what's the exact mechanism to achieve that. How do you mark all existing conda-packages as incompatible with mkl?

**Comment by beckermr** [comment]
We can push a fix to the repo data patches feedstock. I'm happy to push the fix if people agree to it.

**Comment by dalcinl** [comment]
OK. I did not know you could "patch" the repodata. Once we have a new release and respective conda-forge build, I have no problems with it. @mikaem what do you think? Do you have some spare time to make a new release any time soon?

**Comment by beckermr** [comment]
@dalcinl See this PR for the patch. We can merge once a new release is done. https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/139

cc @mikaem

**Comment by mikaem** [comment]
Sorry about the late reply @dalcinl. I'm ready to release now.
